//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitasMedicas
    {
        public int IdCitaMedica { get; set; }
        public string Especialista { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Hora { get; set; }
        public Nullable<int> Minutos { get; set; }
        public Nullable<int> Segundos { get; set; }
        public string EstadoCitas { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
    }
}
