//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class InscripcionesDeportistas
    {      
        public int IdIncripcionBeneficiarios { get; set; }
        [Required(ErrorMessage = "El Programa es obligatorio.")]
        public string ProgramaInscripciones { get; set; }
        public string DocumentoPdf { get; set; }
        public string SaludPdf { get; set; }
        public string AutorizacionPdf { get; set; }
        public string CedulaPadrePdf { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        public string TipoIdentificacionInscripciones { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        public Nullable<long> NumIdentificacionInscripciones { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        public string PrimerNombreInscripciones { get; set; }
        [Required(ErrorMessage = "El segundo nombre es obligatorio.")]
        public string SegundonombreInscripciones { get; set; }
        [Required(ErrorMessage = "El primer apellido es obligatorio.")]
        public string PrimerApellidoInscripciones { get; set; }
        [Required(ErrorMessage = "El segundo apellido es obligatorio.")]
        public string SegundoApellidoInscripciones { get; set; }
        [Required(ErrorMessage = "La fecha de nacimiento es obligatoria.")]
        [DataType(DataType.Date)]
        public string FechaNacimientoInscripciones { get; set; }
        [Required(ErrorMessage = "La edad es obligatorio.")]
        public Nullable<long> EdadInscripciones { get; set; }
        [Required(ErrorMessage = "El Pais es obligatorio.")]
        public string PaisNacimientoInscripciones { get; set; }
        [Required(ErrorMessage = "El departamento es obligatorio.")]
        public string DepartamentoInscripciones { get; set; }
        [Required(ErrorMessage = "El municipio es obligatorio.")]
        public string MunicipioInscripciones { get; set; }
        [Required(ErrorMessage = "El genero apellido es obligatorio.")]
        public string GeneroInscripciones { get; set; }
        [Required(ErrorMessage = "El grupo etarreo es obligatorio.")]
        public string GrupoEtarreoInscripciones { get; set; }
        [Required(ErrorMessage = "La dirreccion de residencia es obligatorio.")]
        public string DireccionResidencia { get; set; }
        [Required(ErrorMessage = "El barrio de residencia es obligatorio.")]
        public string BarrioResidencia { get; set; }
        [Required(ErrorMessage = "El municipio residencia es obligatorio.")]
        public string MunicipioResidencia { get; set; }
        [Required(ErrorMessage = "El estrato es obligatorio.")]
        public string EstratoResidencia { get; set; }
        [Required(ErrorMessage = "La zona residencia es obligatorio.")]
        public string ZonaResidencia { get; set; }
        [Required(ErrorMessage = "El telefono es obligatorio.")]
        public string TelefonoResidencia { get; set; }
        [Required(ErrorMessage = "El correo es obligatorio.")]
        public string CorreoResidencia { get; set; }
        [Required(ErrorMessage = "El estado civil es obligatorio.")]
        public string EstadoCivil { get; set; }
        [Required(ErrorMessage = "El nivel de estudio es obligatorio.")]
        public string NivelEstudio { get; set; }
        [Required(ErrorMessage = "El segimen de salud es obligatorio.")]
        public string RegimenSalud { get; set; }
        [Required(ErrorMessage = "La eps es obligatorio.")]
        public string Eps { get; set; }
        [Required(ErrorMessage = "El tipo de sangre es obligatorio.")]
        public string Tiposangre { get; set; }
        [Required(ErrorMessage = "El tipo de condicion de poblacion es obligatorio.")]
        public string CondicionPoblacion { get; set; }
        [Required(ErrorMessage = "El tipo de discapacidad es obligatorio.")]
        public string DiscapacidadPoblacion { get; set; }
        [Required(ErrorMessage = "El tipo de grupo etnico es obligatorio.")]
        public string GrupoEtnico { get; set; }
        [Required(ErrorMessage = "El tipo de deporte es obligatorio.")]
        public string DeportePractica { get; set; }
        [Required(ErrorMessage = "El tipo de nombre entrenador es obligatorio.")]
        public string NombreEntrenador { get; set; }
        [Required(ErrorMessage = "El tipo de nombre de contacto es obligatorio.")]
        public string NombreContacto { get; set; }
        [Required(ErrorMessage = "El telefono es obligatorio.")]
        public string TelefonoContacto { get; set; }
        [Required(ErrorMessage = "El correo es obligatorio.")]
        public string CorreoContacto { get; set; }
    }
}
