//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionesDeportistas
    {
        public int IdIncripcionBeneficiarios { get; set; }
        public string ProgramaInscripciones { get; set; }
        public string TipoIdentificacionInscripciones { get; set; }
        public Nullable<long> NumIdentificacionInscripciones { get; set; }
        public string PrimerNombreInscripciones { get; set; }
        public string SegundonombreInscripciones { get; set; }
        public string PrimerApellidoInscripciones { get; set; }
        public string SegundoApellidoInscripciones { get; set; }
        public string FechaNacimientoInscripciones { get; set; }
        public Nullable<long> EdadInscripciones { get; set; }
        public string PaisNacimientoInscripciones { get; set; }
        public string DepartamentoInscripciones { get; set; }
        public string MunicipioInscripciones { get; set; }
        public string GeneroInscripciones { get; set; }
        public string GrupoEtarreoInscripciones { get; set; }
        public string DireccionResidencia { get; set; }
        public string BarrioResidencia { get; set; }
        public string MunicipioResidencia { get; set; }
        public string EstratoResidencia { get; set; }
        public string ZonaResidencia { get; set; }
        public string TelefonoResidencia { get; set; }
        public string CorreoResidencia { get; set; }
        public string EstadoCivil { get; set; }
        public string NivelEstudio { get; set; }
        public string RegimenSalud { get; set; }
        public string Eps { get; set; }
        public string Tiposangre { get; set; }
        public string CondicionPoblacion { get; set; }
        public string DiscapacidadPoblacion { get; set; }
        public string GrupoEtnico { get; set; }
        public string DeportePractica { get; set; }
        public string NombreEntrenador { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string CorreoContacto { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
