//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicos
    {
        public int IdMedicos { get; set; }
        public Nullable<int> CodMedicos { get; set; }
        public string EstadoEspecialistas { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Especialidad { get; set; }
        public string Direcccion { get; set; }
        public string Telefono { get; set; }
        public string Centro { get; set; }
        public string Genero { get; set; }
        public string Correo { get; set; }
    }
}
